### ISSUE TITLE
Initial plugin suggestions

### ISSUE THREAD

**Issue by misraved** [francois2metz/steampipe-plugin-ovh#1]
Thanks @francois2metz for another great plugin. 

I have a couple of minor suggestions, please let me know if you have any questions about them -

- Can we update the `short_name: "OVH"` to `short_name: "ovh"` ? We typically use lower case letters while calling out `short_name` in the `docs/index.md` file. 
- Can we remove the `,` appended at the end of the last column name in a few example queries? For instance, I believe we should update `status,` to `status` [here](https://github.com/francois2metz/steampipe-plugin-ovh/blob/main/docs/tables/ovh_cloud_data_job.md#list-data-job-of-a-cloud-project) since it returns a syntax error.
- Can we update the descriptions of column names of tables to use `ID` instead of `id`. For example, we could use `Project ID` instead of `Project id` [here](https://github.com/francois2metz/steampipe-plugin-ovh/blob/main/ovh/table_ovh_cloud_data_job.go#L33)

**Comment by francois2metz** [comment]
Hi!
Thanks for your review. I fixed all the points.

**Comment by cbruno10** [comment]
Hey @francois2metz , thanks for making changes so quickly above, and sorry it took us so long to respond!

We had another look at the plugin, and had a few more questions/suggestions:
- For all tables, is pagination handled in the SDK or API? Is this something we need to handle in the plugin tables?
- For the table `description` fields, can we use the one line descriptions from the table docs? For instance, in `ovh_cloud_flavor`, the description says "Get flavors.", but the table doc has the description, "A flavor is the instance model defining its characteristics in terms of resources.", which feels a little more complete.
- Should the `ovh_cloud_sshkey` table be named `ovh_cloud_ssh_key` instead to keep with snake case like the other tables are?
- In `config/ovh.spc`, will all users go to "https://eu.api.ovh.com/createToken/" to create a token, or if they use another region, would they use a different URL?
- Also in `config/ovh.spc`, can you please add dummy values in the same format for the `application_key`, `application_secret`, `consumer_key` arguments? For instance, please see our [Duo config file](https://github.com/turbot/steampipe-plugin-duo/blob/main/config/duo.spc#L10-L13).
- For the table docs that only have 1 example, can you please add 1-2 more queries to those, similar to the table docs for `ovh_cloud_data_job` and `ovh_cloud_volume`? This will help fill out those pages on the Hub more and provide users with helpful examples to get started.

Thanks again for creating this plugin and please let me know if you have any questions!

**Comment by francois2metz** [comment]
Hi @cbruno10 
 
>     * For all tables, is pagination handled in the SDK or API? Is this something we need to handle in the plugin tables?

This seems that there is no pagination in their API.

>     * For the table `description` fields, can we use the one line descriptions from the table docs? For instance, in `ovh_cloud_flavor`, the description says "Get flavors.", but the table doc has the description, "A flavor is the instance model defining its characteristics in terms of resources.", which feels a little more complete.
> 
>     * Should the `ovh_cloud_sshkey` table be named `ovh_cloud_ssh_key` instead to keep with snake case like the other tables are?
> 
>     * In `config/ovh.spc`, will all users go to "https://eu.api.ovh.com/createToken/" to create a token, or if they use another region, would they use a different URL?
> 
>     * Also in `config/ovh.spc`, can you please add dummy values in the same format for the `application_key`, `application_secret`, `consumer_key` arguments? For instance, please see our [Duo config file](https://github.com/turbot/steampipe-plugin-duo/blob/main/config/duo.spc#L10-L13).
> 
>     * For the table docs that only have 1 example, can you please add 1-2 more queries to those, similar to the table docs for `ovh_cloud_data_job` and `ovh_cloud_volume`? This will help fill out those pages on the Hub more and provide users with helpful examples to get started.

I did all above suggestions.

**Comment by cbruno10** [comment]
Thanks @francois2metz ! v0.0.3 looks ready to be published to the Hub, so I've started the process just now to publish it.
